### ISSUE TITLE
Sidebar navigation in Workbooks

### ISSUE THREAD

**Issue by xyntechx** [xyntechx/NexLiber#15]
### Why
Allow users to get an overview of the Workbook and jump to different titles. This improves the learning experience.

### TODO
- [ ] Ref https://www.cyishere.dev/blog/toc-for-mdx-with-nextjs
- [ ] Build sidebar with `a` tags with `href="#some-title"`
- [ ] Include `id="some-title"` in `h1` tags for section headers
