### ISSUE TITLE
🔖 2.0.0

### ISSUE THREAD

**Issue by xyntechx** [xyntechx/NexLiber#3]
# Change logo
- See #4 
- New logo looks nicer & is more representative of "Next Library" (book with arrow) while still maintaining the "level up" mentality (up arrow)

# Dark Mode default
- 👀 😎
- Can switch between ☀️ & 🌑

# Use Sanity for Creators
## Why
- Better Creator experience
- Minimise source code size (this repo)
## TODO
- [ ] Update `projects.json` in Sanity -- [docs](https://www.sanity.io/docs/custom-input-widgets)
- [ ] Override default Sanity publish button (keeps default behaviour but also creates a PR on `projects.json`) -- [docs](https://www.sanity.io/docs/document-actions) + [q&a](https://www.sanity.io/answers/disable-the-publish-button-for-a-subset-of-p1600372123262400) + [more docs](https://www.sanity.io/docs/document-actions-api) + [github gh pr create docs](https://cli.github.com/manual/gh_pr_create) + [stackoverflow github](https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action) + [github api edit file docs](https://docs.github.com/en/rest/repos/contents)
- [ ] `/workbook/[title]` must check whether `title` is a key in `projects.json`; show Workbook if yes but 404 if no
- [ ] Implement **Quiz** (maybe **Pic**) on Sanity -- [docs](https://www.sanity.io/docs/customization) & [more docs](https://www.sanity.io/docs/configuration)
- [ ] Code block syntax highlighting with Sanity (remove CodeHike deps) -- [how-to](https://dev.to/hosenur/implementing-code-input-highlighting-in-next-js-sanity-blog-40he)
- [ ] Remove MDX deps
- [ ] Still use **WorkbookLayout**

# Update docs accordingly
- This is a given :p
