### ISSUE TITLE
Prisma + `/creator` + `/admin`

### ISSUE THREAD

**Issue by xyntechx** [xyntechx/NexLiber#7]
### Why
- Better Creator experience
- Minimise source code size (this repo)

### TODO
- [ ] Create `/creator` page which acts as a form to submit Workbook draft
- [ ] In `/creator`, build buttons to select different input fields for different components (e.g. header, paragraph, quiz)
- [ ] Integrate a database to store Workbooks and Workbook drafts
- [ ] Create `/admin` page to promote Workbook drafts to Workbooks (approve drafts)
- [ ] Implement progressive loading when getting data from database (6 Workbooks shown in the Library at first + `See More` button to load 6 more Workbooks on each click)
